ln -sfv ~/dotfiles/.bash_ps1 ~/.bash_ps1
ln -sfv ~/dotfiles/bash/bash_profile ~/.bash_profile
ln -sfv ~/dotfiles/bashrc ~/.bashrc
ln -sfv ~/dotfiles/ackrc ~/.ackrc
ln -sfv ~/dotfiles/.bash_dont_think.sh ~/.bash_dont_think.sh
ln -sfv ~/dotfiles/.git-completion.bash ~/.git-completion.bash
ln -sfv ~/dotfiles/.vimrc ~/.vimrc
ln -sfv ~/dotfiles/.vim ~/.vim
ln -sfv ~/dotfiles/.zshrc ~/.zshrc
